<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>LocalModManager.Abstractions</AssemblyName>
    <RootNamespace>LocalModManager.Abstractions</RootNamespace>
    <Version>1.0.0</Version>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <DebugType>none</DebugType>
  </PropertyGroup>
</Project>
